# Generated by Django 5.1.6 on 2025-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_blood_group_user_description_user_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
